# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

tips:
  - 为什么一个博客会和游戏一样有 tips 功能呢...
  - 真的有人认为这是一个技术向博客吗，不会吧不会吧？
  - 为什么网页打开慢啊，还不都是因为博主往里面塞老多字体和图片！
  - 猜猜 cover 里的图片的出处是哪儿呢？
  - 你觉得会有多少条 tips 啊...
  - 感兴趣的话，能评价下这主题好看吗...
  - 我永远喜欢神户小鸟（大声）！
  - 有人会看这博客里的内容吗（提出疑问）...
  - 不知道加载速度够不够你读完这条 tips...
  - 会不会有人专门为了看 tips 点开 Devtools 啊...
  - 所有 tips 都是乱写的，包括这一条...
  - 所有 tips 都是认真的，不包括这一条...
  - 少女祈祷中...
  - 咕咕咕？咕咕，咕咕咕！咕咕咕咕咕咕咕...
  - 啊哈！
  - 你知道吗，这个功能在某些游戏里叫 tips...
  - 其实点开文章还可以在左上角听音乐哦...
  - 哎，感觉自己已经是个老年退役选手了呐...
  - 在 tips 里面...放什么都可以吧？
  - tips 的出现概率...真的是随机的！
  - 如果人生可以重来，你还愿意成为竞赛生吗...
  - ♩ 夢ならば覚めないで ♩
  - ♩ Memories are here ~ fragile souvenir ~ ♩
  - 「友情是珍珠，回忆是钻石」
  - 「纵然已经踏上不归之路，也绝对不要回头呢」

# 默认音乐（随机播放）
mp3: 
  - /music/観月あんみ - Memories are here (クロハネエンディング).mp3
  - /music/やなぎなぎ - 恋文.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: 

# 默认文章封面图（随机调用,支持外链）
cover: 
  - https://static.memset0.cn/img/v2/20201021093955.png
 
# 是否使用mathjax
mathjax: true

# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
  # 是否启用
  enable: true

# 是否显示 一言(hitokoto)
hitokoto: false

# 链接(可选:facebook,twitter,github,wechat,email)
links:
  facebook: /
  twitter: /
  github: /
  wechat: /img/logo.png
  email: mailto:xxxx@gmail.com

# 备案
beian: 
  # 是否显示备案信息
  enable: false
  # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
  enableFooter: false
  # 备案号
  beianInfo: 冀ICP备xxxxxxx号
  # 链接地址
  link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
  # 是否启用评论功能
  enable: true
  # 是否自动展开评论框
  autoExpand: true
  # 应用编号
  clientID: 9a58625d1ff4c0e473ac
  # 应用秘钥
  clientSecret: 6a26bac24632719df98b6c266dbb57931253ebf1
  # issue仓库名
  repo: new-blog
  # Github名
  owner: memset0
  # Github名
  admin: [memset0]
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction free mode
  distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
